version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-gs
    restart: no
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    networks:
      gs-network:
        ipv4_address: 170.30.0.100
    ports:
      - "1883:1883"
      - "9001:9001"

  influxdb:
    image: influxdb:2.4-alpine
    container_name: influxdb-gs
    restart: no
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=se4iot_token
      - DOCKER_INFLUXDB_INIT_ORG=se4iot
      - DOCKER_INFLUXDB_INIT_BUCKET=gs_sensors
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
    ports:
      - '8086:8086'
    volumes:
      - ./influxdb_data:/var/lib/influxdb
    networks:
      gs-network:
        ipv4_address: 170.30.0.102

  grafana:
    image: grafana/grafana
    container_name: grafana-server-gs
    restart: no
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      gs-network:
        ipv4_address: 170.30.0.103

  telegraf:
    image: telegraf
    container_name: telegraf-gs
    restart: no
    volumes:
    - ./telegraf:/etc/telegraf:ro
    depends_on:
      - influxdb
      - mqtt
    links:
      - influxdb
    ports:
      - '8125:8125'    
    networks:
      gs-network:
        ipv4_address: 170.30.0.101

networks:
  gs-network:
    driver: bridge
    ipam:
      config:
        - subnet: 170.30.0.0/16